export const ICON_PROFILE = '.tt-account > .tt-dropdown-toggle'
export const ICON_PROFILE_NAME = '.tt-account > .tt-dropdown-toggle > .tt-account-name'
export const TEXT_TITLE_CENTER = '#product-collection-1521705360339 > .container > .custom-block-title > div > .tt-title'
export const ICON_SEARCH = '.tt-search > .tt-dropdown-toggle'
export const INPUT_SEARCH = '#boost-pfs-search-box-0'