export const TITLE_LOGIN = '#login > .tt-title'
export const BUTTON_LOGIN = '#btn-login'
export const TEXT_ERROR_MESSAGE = '.errors'
export const INPUT_USERNAME = '#loginInputName'
export const INPUT_PASSWORD = '#loginInputPassword'